### ISSUE TITLE
Piatto-Dark?

### ISSUE THREAD

**Issue by Shakil-Shahadat** [kovv/piatto-light#2]
Hi, thanks for the piatto-light theme for the atom editor. Can you please also convert piatto-dark for the atom?

**Comment by kovv** [comment]
I believe that dark themes bad for eyes. But you can do it by yourself using [this tool](https://atom.io/docs/latest/converting-a-text-mate-theme) and covert [this file](https://raw.githubusercontent.com/samuelrafo/piatto/master/Piatto%20Dark.tmTheme).
